### ISSUE TITLE
Arquivo de poster para cada evento

### ISSUE THREAD

**Issue by gnramos** [gnramos/maratona-site-dvl#1]
Deve-se manter a imagem de poster para cada evento? Se sim, é necessário manter a imagem em alta resolução?

**Comment by CarlosE-Ferreira** [comment]
Sim, não precisa ser em alta resolução.

**Comment by gnramos** [comment]
E no caso de divulgação do evento "atual"? Deixa o arquivo de alta resolução e, ao criar um novo evento, substitui por um de baixa?

**Comment by CarlosE-Ferreira** [comment]
Sim, no atual o arquivo com a resolução, caso alguém queira imprimir. Obrigado!

**Comment by gnramos** [comment]
Resolução: considerar que são 2 arquivos com resoluções baixa/alta pra cada evento Nacional (poster_low.png e poster_high.png).
