### ISSUE TITLE
Arquivos Consun 1996

### ISSUE THREAD

**Issue by gnramos** [gnramos/maratona-site-dvl#2]
Os links para os arquivos estão quebrados na página sobre o [I COSUN](https://maratona.sbc.org.br/hist/1996/96_inicial.html). Onde estão os arquivos?

**Comment by CarlosE-Ferreira** [comment]
Você diz o regulamento? Se perdeu com o tempo... Não temos mais

**Comment by gnramos** [comment]
Sem solução.
